"""
Django settings for market project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-set-SECRET_KEY-in-env-for-production'
    else:
        raise ValueError(
            'SECRET_KEY environment variable must be set in production. '
            'Generate one with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"'
        )

# Allow production domain and all Vercel preview URLs (*.vercel.app)
_allowed = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'bu-marketplace.vercel.app').split(',') if h.strip()]
if os.getenv('VERCEL'):
    _allowed.append('.vercel.app')
    if os.getenv('VERCEL_URL'):
        _allowed.append(os.getenv('VERCEL_URL'))
ALLOWED_HOSTS = _allowed

_origins = [o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', 'https://bu-marketplace.vercel.app').split(',') if o.strip()]
if os.getenv('VERCEL') and os.getenv('VERCEL_URL'):
    _origins.append('https://' + os.getenv('VERCEL_URL'))
CSRF_TRUSTED_ORIGINS = _origins

# Production security: secure cookies and HSTS when not in debug mode
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 300
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # If your app is behind a reverse proxy that terminates SSL, set SECURE_PROXY_SSL_HEADER
    # e.g. SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'market_app',
    'crispy_forms',
    'crispy_bootstrap5',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def _env(key, default=None):
    """Get env var and strip optional surrounding quotes."""
    val = os.getenv(key, default)
    if val is None or not isinstance(val, str):
        return val
    val = val.strip()
    if (len(val) >= 2 and
            ((val[0] == "'" and val[-1] == "'") or (val[0] == '"' and val[-1] == '"'))):
        return val[1:-1].strip()
    return val


# On Vercel static build (build.sh runs migrate/collectstatic), use SQLite so we don't
# need the Postgres driver during build. At runtime (wsgi) we use Postgres from DATABASE_URL.
if os.getenv('VERCEL') and len(sys.argv) > 1 and sys.argv[1] in ('collectstatic', 'migrate', 'makemigrations'):
    DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': ':memory:'}}
else:
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600)  # connection pooling
    }


AUTHENTICATION_BACKENDS = [
    'market_app.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = 'home'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles_build" / "static"

# Supabase Storage Configuration (S3-compatible)
SUPABASE_URL = os.getenv('SUPABASE_URL', 'https://nvumdffvsysdmpruyhyu.supabase.co')
SUPABASE_KEY = os.getenv('SUPABASE_KEY')
SUPABASE_PROJECT_ID = os.getenv('SUPABASE_PROJECT_ID', 'nvumdffvsysdmpruyhyu')

# Django Storages - S3 compatible settings for Supabase
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": "product-images",
            "endpoint_url": f"https://{SUPABASE_PROJECT_ID}.supabase.co/storage/v1/s3",
            "access_key": os.getenv('SUPABASE_S3_ACCESS_KEY'),
            "secret_key": os.getenv('SUPABASE_S3_SECRET_KEY'),
            "region_name": "us-east-1",
            "default_acl": "public-read",
            "querystring_auth": False,
            "custom_domain": f"{SUPABASE_PROJECT_ID}.supabase.co/storage/v1/object/public/product-images",
        },
    },
    "profile_images": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": "profile-images",
            "endpoint_url": f"https://{SUPABASE_PROJECT_ID}.supabase.co/storage/v1/s3",
            "access_key": os.getenv('SUPABASE_S3_ACCESS_KEY'),
            "secret_key": os.getenv('SUPABASE_S3_SECRET_KEY'),
            "region_name": "us-east-1",
            "default_acl": "public-read",
            "querystring_auth": False,
            "custom_domain": f"{SUPABASE_PROJECT_ID}.supabase.co/storage/v1/object/public/profile-images",
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'
