# Generated by Django 6.0.2 on 2026-02-27 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
