# Generated by Django 6.0.2 on 2026-03-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0006_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
