# Generated by Django 6.0.2 on 2026-03-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0007_remove_category_description'),
        ('market_app', '0007_remove_category_description_inquiry'),
    ]

    operations = [
    ]
