# Generated by Django 6.0.2 on 2026-03-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0007_remove_category_description_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='years_of_use',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
