# Generated by Django 6.0.2 on 2026-03-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0008_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='uploaded_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20),
        ),
    ]
