# Generated by Django 6.0.2 on 2026-03-05 02:09

from django.db import migrations


def migrate_images_forward(apps, schema_editor):
    """Copy existing Product.image values to ProductImage records."""
    Product = apps.get_model('market_app', 'Product')
    ProductImage = apps.get_model('market_app', 'ProductImage')
    
    for product in Product.objects.exclude(image='').exclude(image__isnull=True):
        ProductImage.objects.create(
            product=product,
            image=product.image,
            position=0
        )


def migrate_images_backward(apps, schema_editor):
    """Restore Product.image from first ProductImage (for rollback)."""
    Product = apps.get_model('market_app', 'Product')
    ProductImage = apps.get_model('market_app', 'ProductImage')
    
    for product in Product.objects.all():
        first_image = ProductImage.objects.filter(product=product).order_by('position', 'created_at').first()
        if first_image:
            product.image = first_image.image
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0009_add_productimage'),
    ]

    operations = [
        migrations.RunPython(migrate_images_forward, migrate_images_backward),
    ]
