# Generated by Django 6.0.2 on 2026-03-05 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0009_remove_category_description_inquiry_uploaded_video_and_more'),
        ('market_app', '0010_migrate_existing_images'),
    ]

    operations = [
    ]
