# Generated by Django 6.0.2 on 2026-03-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0011_merge_20260305_0357'),
        ('market_app', '0011_merge_20260305_0451'),
    ]

    operations = [
    ]
